# Generated by Django 4.1.4 on 2023-05-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='StallName2',
            field=models.CharField(default='', max_length=50),
        ),
    ]
