# Generated by Django 4.1.4 on 2023-05-18 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stall', '0002_product_stallname2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stall',
            old_name='Url',
            new_name='url',
        ),
    ]
