# Generated by Django 4.2.1 on 2023-05-25 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stall', '0007_alter_order_user_alter_orderitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryinfo',
            old_name='FloorNo',
            new_name='Phone',
        ),
    ]
