# Generated by Django 4.2.1 on 2023-05-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stall', '0008_rename_floorno_deliveryinfo_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryinfo',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
