# Generated by Django 4.2.1 on 2023-05-29 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stall', '0009_deliveryinfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryinfo',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
