# Generated by Django 4.2.1 on 2023-06-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stall', '0010_deliveryinfo_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryinfo',
            name='semester',
            field=models.CharField(choices=[('Preparing', 'Preparing'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], default='Preparing', max_length=20),
        ),
    ]
