# Generated by Django 4.1.4 on 2023-04-07 15:44

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_contact_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=10, region=None),
        ),
    ]
