# Generated by Django 4.1.4 on 2023-05-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_carousel_food_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='img_title',
            field=models.CharField(default='Food', max_length=20),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='food_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
