# Generated by Django 4.1.4 on 2023-05-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_carousel_food_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamousItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_title', models.CharField(default='Food', max_length=20)),
                ('food_img', models.ImageField(upload_to='foodimg')),
                ('food_desc', models.CharField(default='Mouth watering', max_length=100)),
                ('item_price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='carousel',
        ),
    ]
