# Generated by Django 4.1.4 on 2023-05-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_famousitems_delete_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famousitems',
            name='food_desc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='famousitems',
            name='img_title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
